
standaloneAddContents({
  code: "castor_2014",
  title: "Concours Castor 2014",
  folder: "2014/",
  tasks: [
    { code: "2014-CH-05-abacus",
      title: "Boulier (a)" },
    { code: "2014-CH-05-abacus",
      title: "Boulier (b)",
      options: {difficulty: "hard"} },
    { code: "2014-FR-20-shell",
      title: "Terminal (a)",
      options: {difficulty: "easy"} },
    { code: "2014-FR-20-shell",
      title: "Terminal (b)",
      options: {difficulty: "hard"} },
    { code: "2014-FR-03-monster",
      title: "Attraper le monstre" },
    { code: "2014-FR-06-bridge",
      title: "Traverser le pont (a)",
      options: {difficulty: "easy"} },
    { code: "2014-FR-06-bridge",
      title: "Traverser le pont (b)",
      options: {difficulty: "hard"} },
    { code: "2014-FR-08-maze",
      title: "Deux billes",
      options: {difficulty: "hard"} },
    { code: "2014-FR-04-gattaca",
      title: "Le défi",
      options: {difficulty: "hard"} },
    { code: "2014-FR-05-laser",
      title: "Laser" },
    { code: "2014-SI-02-alien-language",
      title: "Langage alien" },
    { code: "2014-FR-19-summed-row",
      title: "Position secrète (a)",
      options: {difficulty: "easy"} },
    { code: "2014-FR-19-summed-row",
      title: "Position secrète (b)",
      options: {difficulty: "hard"} },
    { code: "2014-TW-05-summed-area",
      title: "Carte secrète" },
    { code: "2014-AU-02-pancake-flipping",
      title: "Retourner les crêpes (a)",
      options: {difficulty: "easy"} },
    { code: "2014-AU-02-pancake-flipping",
      title: "Retourner les crêpes (b)",
      options: {difficulty: "hard"} },
    { code: "2014-AU-02-pancake-flipping",
      title: "Davantage de crêpes",
      options: {difficulty: "many"} },
    { code: "2014-NL-01-secret-number",
      title: "Retenir un code",
      options: {difficulty: "easy"} },
    { code: "2014-SI-04-unknown-friendship",
      title: "Les amis (a)",
      options: {difficulty: "easy"} },
    { code: "2014-SI-04-unknown-friendship",
      title: "Les amis (b)",
      options: {difficulty: "hard"} },
    { code: "2014-RU-04-carrot-storehouses",
      title: "Pièces d'or" },
    { code: "2014-CA-02-shout-your-name",
      title: "Discours familiaux" },
    { code: "2014-SK-01-sticker",
      title: "Autocollants" },
    { code: "2014-SE-04-height-game",
      title: "Parapente (a)",
      options: {difficulty: "easy"} },
    { code: "2014-SE-04-height-game",
      title: "Parapente (b)",
      options: {difficulty: "hard"} },
    { code: "2014-SP-02-traffic",
      title: "Grande réunion" },
    { code: "2014-CH-07-rectangles",
      title: "Dessin interactif",
      options: {difficulty: "hard"} }
   ]
  });


