
standaloneAddContents({
  code: "castor_2010",
  title: "Concours Castor Suisse 2010",
  folder: "2010/",
  tasks: [
    { code: "2010-a-gauche",
      title: "À gauche !" },
    { code: "2010-apprendre-anglais",
      title: "Apprendre l'anglais" },
    { code: "2010-approvisionnement-eau",
      title: "Approvisionnement" }, // Approvisionnement en eau
    { code: "2010-art-castor",
      title: "L'art de Castor" },
    { code: "2010-bits-egaux",
      title: "Tous bits égaux" },
    { code: "2010-castor-sportif",
      title: "Castor sportif" },
    { code: "2010-chemin-plus-court",
      title: "Le chemin le plus court" },
    { code: "2010-chercher-remplacer",
      title: "Chercher remplacer" },
    { code: "2010-circuit-course",
      title: "Circuit de course" },
    { code: "2010-coder-images",
      title: "Coder des images" },
    { code: "2010-couverture-maximale",
      title: "Couverture maximale" },
    { code: "2010-cuisson-au-four",
      title: "Cuisson au four" },
    { code: "2010-decoupeuse",
      title: "La découpeuse" },
    { code: "2010-excursion-photos",
      title: "Excursion photos" },
    { code: "2010-fichiers-desordre",
      title: "Fichiers en désordre" },
    { code: "2010-heure-pandore",
      title: "À l'heure de Pandore" },
    { code: "2010-jeu-tri",
      title: "Jeu de tri" },
    { code: "2010-logique-approvisionnement",
      title: "Approvisionnement 2" },  // Logique de l'approvisionnement en eau
    { code: "2010-miroir-photo",
      title: "Miroir ou photo" },
    { code: "2010-ox",
      title: "OX" },
    { code: "2010-paves",
      title: "Pavés" },
    { code: "2010-photo-classe",
      title: "Photo de classe" },
    { code: "2010-pile-assiettes",
      title: "Pile d'assiettes" },
    { code: "2010-pomme-pin",
      title: "Pomme de pin" },
    { code: "2010-quatre-grenouilles",
      title: "Quatre grenouilles" },
    { code: "2010-rouge-vert-bleu",
      title: "Rouge, vert, bleu" },
    { code: "2010-scarabee-robot",
      title: "Le Scarabée-robot" },
    { code: "2010-soyons-logiques",
      title: "Soyons logiques" },
    { code: "2010-strategie-gagnante",
      title: "Stratégie gagnante" },
    { code: "2010-t9",
      title: "T9" },
    { code: "2010-tampons",
      title: "Tampons" },
    { code: "2010-tour-canoe",
      title: "Tour en canoë" },
    { code: "2010-transmission-donnees",
      title: "Transmission" }, // Transmission de données
    { code: "2010-travaux-peinture",
      title: "Travaux de peinture" },
    { code: "2010-trier-chiffres",
      title: "Trier des chiffres" },
    { code: "2010-tronc-fleur",
      title: "Du tronc à la fleur" },
    { code: "2010-trouve-la-figure",
      title: "Trouver la figure" },
    { code: "2010-voisinage",
      title: "Voisinage" }
   ]
  });



