
standaloneAddContents({
  code: "castor_2012",
  title: "Concours Castor 2012",
  folder: "2012/",
  tasks: [
    { code: "2012-AT-01", 
      title: "Paysage" },
    { code: "2012-AT-04", 
      title: "Image pixellisée" },
    { code: "2012-AT-10", 
      title: "Vélos branchés" },
    { code: "2012-AT-12", 
      title: "Robot bâtisseur" },
    { code: "2012-AT-20", 
      title: "Trier les bâtons" },
    { code: "2012-CA-01", 
      title: "Changer les flèches" },
    { code: "2012-CH-09", 
      title: "La scierie" },
    { code: "2012-CZ-04", 
      title: "Bébrocarina" },
    { code: "2012-CZ-12", 
      title: "Labyrinthe" },
    { code: "2012-DE-01", 
      title: "Réseau de Castoria" },
    { code: "2012-DE-02", 
      title: "Places au cinéma" }, // Choisir les places au cinéma
    { code: "2012-DE-03", 
      title: "Castors aveugles" }, // Accessibilité du web pour les castors aveugles
    { code: "2012-DE-05", 
      title: "Plantons des fleurs" },
    { code: "2012-DE-07", 
      title: "Sélection de robots" },
    { code: "2012-DE-10", 
      title: "Groupe de travail" },
    { code: "2012-ES-04", 
      title: "Tuyauterie" },
    { code: "2012-FI-03", 
      title: "Code castor" },
    { code: "2012-FR-01", 
      title: "Course de grenouilles" },
    { code: "2012-FR-02b", 
      title: "Ranger ses photos" },
    { code: "2012-FR-04", 
      title: "Anonymisation" },
    { code: "2012-FR-04b", 
      title: "Chez le dentiste" },
    { code: "2012-FR-06", 
      title: "Trombone rouge" },
    { code: "2012-FR-07", 
      title: "Territoire de Castor" },
    { code: "2012-FR-08", 
      title: "Dessine un castor" },
    { code: "2012-FR-09", 
      title: "Découpe" },
    { code: "2012-FR-10", 
      title: "La chute" },
    { code: "2012-HU-01a", 
      title: "Puzzle rotatif" },
    { code: "2012-HU-06", 
      title: "Généalogie" },
    { code: "2012-IT-04", 
      title: "Navigation" },
    { code: "2012-IT-13", 
      title: "Œufs de Pâques" },
    { code: "2012-JP-05", 
      title: "Cryptage" },
    { code: "2012-LV-02", 
      title: "Transport de troncs" },
    { code: "2012-RU-03", 
      title: "Affichage digital" },
    { code: "2012-RU-05", 
      title: "Tas de pierres" },
    { code: "2012-SI-06", 
      title: "La boîte magique" },
    { code: "2012-SK-02", 
      title: "Machine à textes" },
    { code: "2012-SK-03", 
      title: "Animation" },
    { code: "2012-SK-10", 
      title: "Convocations" },
    { code: "2012-UA-07", 
      title: "Verres" }
   ]
  });


