
standaloneAddContents({
  code: "castor_2011",
  title: "Concours Castor 2011",
  folder: "2011/",
  tasks: [
    { code: "2011-AT-08", 
      title: "Sauts de grenouille" },
    { code: "2011-AT-11", 
      title: "Troncs d'arbre" },
    { code: "2011-AT-12", 
      title: "Couleur des chaussures" },
    { code: "2011-AT-14", 
      title: "Mot de passe" },
    { code: "2011-CH-01", 
      title: "Mosaïque cassée" },
    { code: "2011-CH-02", 
      title: "Mosaïque" },
    { code: "2011-CH-03", 
      title: "Planter des poteaux" },
    { code: "2011-CH-05", 
      title: "Le langage aibi" },
    { code: "2011-CH-10", 
      title: "La pièce manquante" },
    { code: "2011-CZ-02", 
      title: "Plié et découpé" },
    { code: "2011-DE-01", 
      title: "Une vie de plante" },
    { code: "2011-DE-02", 
      title: "CuSphère et QuatreCyl" },
    { code: "2011-DE-03", 
      title: "Cache cache" },
    { code: "2011-DE-19", 
      title: "Boîte de billes" },
    { code: "2011-DE-20", 
      title: "Lancers de dé" },
    { code: "2011-FI-04", 
      title: "Trésor caché" },
    { code: "2011-FR-01", 
      title: "Fenêtre d'impression" },
    { code: "2011-FR-03", 
      title: "Le prénom du héron" },
    { code: "2011-FR-05", 
      title: "Castor bûcheron" },
    { code: "2011-FR-06", 
      title: "Exploration souterraine" },
    { code: "2011-FR-07", 
      title: "Ranger sa chambre" },
    { code: "2011-IL-01", 
      title: "Balance" },
    { code: "2011-IL-04", 
      title: "Rangée de billes" },
    { code: "2011-IL-11", 
      title: "Atteindre 51" },
    { code: "2011-IT-09", 
      title: "Retour à la maison" },
    { code: "2011-IT-14", 
      title: "Canettes et bouteilles" },
    { code: "2011-JP-01", 
      title: "Transport ferroviaire" },
    { code: "2011-JP-06", 
      title: "Prévenir les élèves" },
    { code: "2011-LT-01", 
      title: "Capteur RVB" },
    { code: "2011-LT-12", 
      title: "Graphe d'un dé" },
    { code: "2011-LT-14", 
      title: "Voyage en Lituanie" },
    { code: "2011-NL-08", 
      title: "Alphabet noir et blanc" },
    { code: "2011-NL-11", 
      title: "Castor facteur" },
    { code: "2011-NL-12", 
      title: "Mauvais chapeau" },
    { code: "2011-SK-02", 
      title: "Piles d'assiettes" },
    { code: "2011-SK-06", 
      title: "Robot tortue" },
    { code: "2011-SK-08", 
      title: "Les amies de Lucie" },
    { code: "2011-SK-11", 
      title: "Les photos de Lucie" },
    { code: "2011-UA-07", 
      title: "Championnat d'échecs" }
   ]
  });


