
standaloneAddContents({
  code: "castor_2013",
  title: "Concours Castor 2013",
  folder: "2013/",
  tasks: [
    { code: "2013-SK-01",
      title: "Promenade en forêt" },
    { code: "2013-CZ-05",
      title: "Pièce de puzzle" },
    { code: "2013-SK-05",
      title: "Collier de perles" },
    { code: "2013-FR-06a",
      title: "Pétales de fleur (a)" },
    { code: "2013-FR-06b",
      title: "Pétales de fleur (b)" },
    { code: "2013-FR-09",
      title: "Sauver le prince" },
    { code: "2013-JP-02",
      title: "Tunnels magiques" },
    { code: "2013-AT-02ab",
      title: "Mot de passe" },
    { code: "2013-FR-15",
      title: "Arroser la plante" },
    { code: "2013-SI-01",
      title: "Élève absent" },
    { code: "2013-FR-08",
      title: "Parasols" },
    { code: "2013-SE-02",
      title: "Réseau pas cher" },
    { code: "2013-FR-01",
      title: "Vitrail coloré" },
    { code: "2013-SI-04",
      title: "Taille du collier" },
    { code: "2013-FR-02",
      title: "Castor des anneaux" },
    { code: "2013-FR-13",
      title: "Trier par poids" },
    { code: "2013-FR-05a",
      title: "Robot peintre (a)" },
    { code: "2013-FR-05b",
      title: "Robot peintre (b)" },
    { code: "2013-FR-10a",
      title: "Chercher / remplacer (a)" },
    { code: "2013-FR-10b",
      title: "Chercher / remplacer (b)" },
    { code: "2013-FR-11",
      title: "Transport d'électricité" },
    { code: "2013-FR-12a",
      title: "Choix des invités (a)" },
    { code: "2013-FR-12b",
      title: "Choix des invités (b)" },
    { code: "2013-SK-09ab",
      title: "Dessiner un dé" },
    { code: "2013-RU-05a",
      title: "Parcours de billes (a)" },
    { code: "2013-RU-05b",
      title: "Parcours de billes (b)" },
    { code: "2013-FR-04",
      title: "Boîtes de chocolats" },
    { code: "2013-NL-02",
      title: "Inspection de la rivière" },
    { code: "2013-FR-14",
      title: "Jeu de parité" },
    { code: "2013-DE-02",
      title: "Images aléatoires" },
    { code: "2013-FR-16",
      title: "Sac à dos" }
   ]
  });


